CREATE TABLE `adoption_sources` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`source_system` text NOT NULL,
	`listing_url` text NOT NULL,
	`base_url` text,
	`region` text,
	`city` text,
	`county` text,
	`state` text DEFAULT 'CA' NOT NULL,
	`postal_code` text,
	`latitude` real,
	`longitude` real,
	`geocode_precision` text DEFAULT 'unknown' NOT NULL,
	`phone` text,
	`email` text,
	`website_url` text,
	`contact_url` text,
	`adoption_process_url` text,
	`adoption_application_url` text,
	`hours_url` text,
	`priority` text DEFAULT 'medium' NOT NULL,
	`enabled` integer DEFAULT false NOT NULL,
	`crawl_interval_hours` integer DEFAULT 24 NOT NULL,
	`permission_status` text DEFAULT 'unreviewed' NOT NULL,
	`robots_status` text DEFAULT 'unchecked' NOT NULL,
	`robots_checked_at` integer,
	`source_status_notes` text,
	`safe_for_personal_low_frequency_fetching` integer,
	`blocks_automation` integer,
	`notes` text,
	`adapter_type` text NOT NULL,
	`needs_javascript` integer DEFAULT false NOT NULL,
	`has_pagination` integer,
	`requires_detail_pages` integer,
	`parser_version` text,
	`request_delay_ms` integer DEFAULT 1500 NOT NULL,
	`timeout_ms` integer DEFAULT 25000 NOT NULL,
	`retry_count` integer DEFAULT 2 NOT NULL,
	`max_pages_per_run` integer DEFAULT 40 NOT NULL,
	`max_detail_pages_per_run` integer DEFAULT 200 NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `canonical_dogs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`merge_key` text NOT NULL,
	`display_name` text,
	`display_listing_id` text,
	`listing_count` integer DEFAULT 1 NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `canonical_dogs_merge_key` ON `canonical_dogs` (`merge_key`);--> statement-breakpoint
CREATE TABLE `dog_listings` (
	`id` text PRIMARY KEY NOT NULL,
	`source_id` text NOT NULL,
	`source_system` text NOT NULL,
	`source_animal_id` text,
	`listing_key` text NOT NULL,
	`original_url` text NOT NULL,
	`name` text,
	`species` text,
	`breed_raw` text,
	`breed_normalized` text,
	`age_raw` text,
	`age_months_estimate` integer,
	`sex` text,
	`size_raw` text,
	`size_normalized` text,
	`weight_raw` text,
	`weight_lbs_estimate` real,
	`color_raw` text,
	`colors_normalized` text,
	`status_raw` text,
	`status_normalized` text DEFAULT 'unknown' NOT NULL,
	`availability_date` text,
	`intake_date` text,
	`shelter_name` text,
	`shelter_location_name` text,
	`address` text,
	`city` text,
	`county` text,
	`state` text,
	`postal_code` text,
	`latitude` real,
	`longitude` real,
	`geocode_precision` text DEFAULT 'unknown' NOT NULL,
	`primary_photo_url` text,
	`photo_urls` text,
	`description` text,
	`biography_raw` text,
	`good_with_dogs` integer,
	`good_with_cats` integer,
	`good_with_kids` integer,
	`house_trained` integer,
	`apartment_friendly` integer,
	`energy_level` text,
	`special_needs` text,
	`spayed_neutered` integer,
	`vaccinated` integer,
	`microchipped` integer,
	`adoption_fee` text,
	`urgent_notes` text,
	`foster_notes` text,
	`hold_notes` text,
	`contact_phone` text,
	`contact_email` text,
	`contact_url_override` text,
	`first_seen_at` integer NOT NULL,
	`last_seen_at` integer NOT NULL,
	`missing_since` integer,
	`missed_run_count` integer DEFAULT 0 NOT NULL,
	`stale_status` text DEFAULT 'available' NOT NULL,
	`content_hash` text NOT NULL,
	`photo_hash` text,
	`card_fingerprint` text,
	`detail_fetched_at` integer,
	`raw_payload` text,
	`canonical_dog_id` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`source_id`) REFERENCES `adoption_sources`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `dog_listings_source_listing_key` ON `dog_listings` (`source_id`,`listing_key`);--> statement-breakpoint
CREATE INDEX `dog_listings_source_id` ON `dog_listings` (`source_id`);--> statement-breakpoint
CREATE INDEX `dog_listings_canonical` ON `dog_listings` (`canonical_dog_id`);--> statement-breakpoint
CREATE INDEX `dog_listings_stale` ON `dog_listings` (`stale_status`);--> statement-breakpoint
CREATE TABLE `geocode_cache` (
	`query` text PRIMARY KEY NOT NULL,
	`latitude` real,
	`longitude` real,
	`precision` text NOT NULL,
	`provider` text NOT NULL,
	`resolved_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `saved_searches` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`enabled` integer DEFAULT true NOT NULL,
	`criteria` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `source_runs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`source_id` text NOT NULL,
	`started_at` integer NOT NULL,
	`finished_at` integer,
	`status` text NOT NULL,
	`listings_found` integer DEFAULT 0 NOT NULL,
	`dogs_found` integer DEFAULT 0 NOT NULL,
	`new_dogs` integer DEFAULT 0 NOT NULL,
	`changed_dogs` integer DEFAULT 0 NOT NULL,
	`unchanged_dogs` integer DEFAULT 0 NOT NULL,
	`unavailable_dogs` integer DEFAULT 0 NOT NULL,
	`missing_dogs` integer DEFAULT 0 NOT NULL,
	`error_message` text,
	`parser_version` text,
	`html_hash` text,
	`warnings` text,
	`pages_visited` integer DEFAULT 0 NOT NULL,
	`detail_pages_visited` integer DEFAULT 0 NOT NULL,
	`total_listings_reported_by_source` integer,
	`pagination_completed` integer,
	`detail_extraction_completed` integer,
	`pagination_trace` text,
	`raw_debug_path` text,
	`missing_updates_applied` integer DEFAULT false NOT NULL,
	FOREIGN KEY (`source_id`) REFERENCES `adoption_sources`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `source_runs_source_started` ON `source_runs` (`source_id`,`started_at`);--> statement-breakpoint
CREATE TABLE `user_dog_statuses` (
	`dog_listing_id` text PRIMARY KEY NOT NULL,
	`status` text NOT NULL,
	`notes` text,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`dog_listing_id`) REFERENCES `dog_listings`(`id`) ON UPDATE no action ON DELETE no action
);
