import type { AdapterContext, SourceAdapter } from "./types";
import type { AdapterResult, ExtractedDog } from "@/lib/types";

/**
 * Mock adapter: realistic synthetic California dogs for UI/dev work.
 * Deliberately exercises edge cases: multiple photos, missing photos, broken
 * photo URLs, unknown statuses, holds, fosters, missing coordinates, missing
 * ages/weights, placeholder names, special needs, fees, and contact overrides.
 */

const dog = (d: Partial<ExtractedDog> & Pick<ExtractedDog, "sourceAnimalId" | "originalUrl" | "name">): ExtractedDog => ({
  species: "Dog",
  breedRaw: null,
  ageRaw: null,
  sexRaw: null,
  sizeRaw: null,
  weightRaw: null,
  colorRaw: null,
  statusRaw: null,
  primaryPhotoUrl: null,
  photoUrls: [],
  rawPayload: { mock: true },
  detailFetched: true,
  ...d,
});

export const MOCK_DOGS: ExtractedDog[] = [
  dog({
    sourceAnimalId: "MOCK-001",
    originalUrl: "https://example.org/mock/adopt/frankie",
    name: "Frankie",
    breedRaw: "Dachshund / Chihuahua Mix",
    ageRaw: "6 years",
    sexRaw: "Neutered Male",
    sizeRaw: "Small",
    weightRaw: "12 lbs",
    colorRaw: "Black / Tan",
    statusRaw: "Available",
    city: "San Francisco",
    county: "San Francisco",
    latitude: 37.7583,
    longitude: -122.4267,
    geocodePrecision: "campus",
    primaryPhotoUrl: "https://placedog.net/500/400?id=12",
    photoUrls: [
      "https://placedog.net/500/400?id=12",
      "https://placedog.net/500/401?id=13",
      "https://placedog.net/501/400?id=14",
    ],
    description: "Velcro-level lap companion, office-tested.",
    biographyRaw:
      "Frankie is a mellow little gentleman who wants nothing more than a warm lap and a slow stroll. He walks politely on leash, naps through video calls, and gives world-class side-eye. Already house-trained and quiet in an apartment setting.",
    goodWithDogs: true,
    goodWithCats: null,
    goodWithKids: true,
    houseTrained: true,
    apartmentFriendly: true,
    energyLevel: "low",
    spayedNeutered: true,
    vaccinated: true,
    microchipped: true,
    adoptionFee: "$150",
  }),
  dog({
    sourceAnimalId: "MOCK-002",
    originalUrl: "https://example.org/mock/adopt/juniper",
    name: "Juniper",
    breedRaw: "Australian Cattle Dog",
    ageRaw: "18 months",
    sexRaw: "Female",
    sizeRaw: "Medium",
    weightRaw: "38 lbs",
    colorRaw: "Blue Merle",
    statusRaw: "Adoption Pending",
    city: "Oakland",
    county: "Alameda",
    latitude: 37.7817,
    longitude: -122.2282,
    geocodePrecision: "campus",
    primaryPhotoUrl: "https://placedog.net/500/400?id=22",
    photoUrls: ["https://placedog.net/500/400?id=22", "https://placedog.net/500/402?id=23"],
    biographyRaw:
      "Juniper is a whip-smart heeler who needs a job — hiking partner, agility prospect, or chief squirrel supervisor. Another family is currently meeting her; check back in case it falls through.",
    goodWithDogs: true,
    goodWithCats: false,
    goodWithKids: null,
    houseTrained: null,
    energyLevel: "high",
    spayedNeutered: true,
    vaccinated: true,
    holdNotes: "Adoption pending — meet-and-greet scheduled this week.",
  }),
  dog({
    sourceAnimalId: "MOCK-003",
    originalUrl: "https://example.org/mock/adopt/tamale",
    name: "Tamale",
    breedRaw: "Chihuahua",
    ageRaw: "Senior (est. 11 yrs)",
    sexRaw: "Male",
    sizeRaw: "Small",
    weightRaw: "8.5 lbs",
    colorRaw: "Tan / White",
    statusRaw: "In Foster - Available",
    city: "Berkeley",
    county: "Alameda",
    primaryPhotoUrl: "https://placedog.net/500/400?id=31",
    photoUrls: ["https://placedog.net/500/400?id=31"],
    biographyRaw:
      "Tamale is a dignified senior living his best life in a foster home. Loves sunbeams, soft blankets, and exactly one gentle walk per day. His foster reports he is perfectly house-trained.",
    fosterNotes: "In foster in Berkeley; meet by appointment through the rescue.",
    goodWithDogs: true,
    goodWithCats: true,
    goodWithKids: true,
    houseTrained: true,
    apartmentFriendly: true,
    energyLevel: "low",
    spayedNeutered: true,
    specialNeeds: "Early kidney disease — needs a prescription diet.",
    contactEmail: "tamale-foster@example.org",
  }),
  dog({
    sourceAnimalId: "MOCK-004",
    originalUrl: "https://example.org/mock/adopt/bruno",
    name: "Bruno",
    breedRaw: "German Shepherd Mix",
    ageRaw: "2 years",
    sexRaw: "Male",
    sizeRaw: "Large",
    weightRaw: "72 lbs",
    colorRaw: "Black / Brown",
    statusRaw: "Stray Wait",
    city: "San Jose",
    county: "Santa Clara",
    latitude: 37.3382,
    longitude: -121.8863,
    geocodePrecision: "city",
    primaryPhotoUrl: "https://placedog.net/500/400?id=41",
    photoUrls: ["https://placedog.net/500/400?id=41"],
    holdNotes: "Stray hold until 2026-07-04 — owner may reclaim. Available after if unclaimed.",
    vaccinated: null,
    spayedNeutered: false,
  }),
  dog({
    sourceAnimalId: "MOCK-005",
    originalUrl: "https://example.org/mock/adopt/pixel",
    name: "Pixel",
    breedRaw: "Terrier Mix",
    ageRaw: null, // unknown age
    sexRaw: "Female",
    sizeRaw: null,
    weightRaw: null,
    colorRaw: "Brindle",
    statusRaw: "", // unknown status
    city: "Santa Cruz",
    county: "Santa Cruz",
    primaryPhotoUrl: "https://images.scout-mock.invalid/pixel-broken.jpg", // broken on purpose
    photoUrls: ["https://images.scout-mock.invalid/pixel-broken.jpg"],
    biographyRaw: "Scruffy mystery mutt. Details pending intake exam.",
  }),
  dog({
    sourceAnimalId: "MOCK-006",
    originalUrl: "https://example.org/mock/adopt/meatball",
    name: "Meatball",
    breedRaw: "English Bulldog",
    ageRaw: "4 years",
    sexRaw: "Neutered Male",
    sizeRaw: "Medium",
    weightRaw: "55 lbs",
    colorRaw: "White / Brindle",
    statusRaw: "Rescue Only",
    city: "Sacramento",
    county: "Sacramento",
    latitude: 38.5816,
    longitude: -121.4944,
    geocodePrecision: "city",
    primaryPhotoUrl: null, // no photo at all
    photoUrls: [],
    urgentNotes: "RESCUE ONLY — medical: entropion surgery needed. Approved rescues contact the shelter.",
    specialNeeds: "Entropion (eyelid) surgery required.",
    energyLevel: "low",
  }),
  dog({
    sourceAnimalId: "MOCK-007",
    originalUrl: "https://example.org/mock/adopt/goose",
    name: "Goose",
    breedRaw: "Labrador Retriever",
    ageRaw: "10 months",
    sexRaw: "Male",
    sizeRaw: "Large (still growing)",
    weightRaw: "48 lbs",
    colorRaw: "Yellow",
    statusRaw: "Available",
    city: "Novato",
    county: "Marin",
    latitude: 38.0788,
    longitude: -122.5241,
    geocodePrecision: "campus",
    primaryPhotoUrl: "https://placedog.net/500/400?id=52",
    photoUrls: [
      "https://placedog.net/500/400?id=52",
      "https://placedog.net/500/403?id=53",
      "https://placedog.net/502/400?id=54",
      "https://placedog.net/500/404?id=55",
    ],
    biographyRaw:
      "Goose is a big goofy puppy who thinks he is a lap dog. Knows sit and 'gimme paw', working on not eating shoes. Needs a family with time for adolescent-dog training.",
    goodWithDogs: true,
    goodWithKids: true,
    houseTrained: false,
    energyLevel: "very high",
    spayedNeutered: true,
    vaccinated: true,
    microchipped: true,
    adoptionFee: "$250",
  }),
  dog({
    sourceAnimalId: "A1234567", // id-style placeholder name
    originalUrl: "https://example.org/mock/adopt/A1234567",
    name: "A1234567",
    breedRaw: "Pit Bull Terrier",
    ageRaw: "3 years",
    sexRaw: "Female",
    sizeRaw: "Medium",
    weightRaw: "51 lbs",
    colorRaw: "Gray / White",
    statusRaw: "ID HOLD",
    city: "Riverside",
    county: "Riverside",
    primaryPhotoUrl: "https://placedog.net/500/400?id=61",
    photoUrls: ["https://placedog.net/500/400?id=61"],
    holdNotes: "ID hold — possible owner identification in progress.",
  }),
  dog({
    sourceAnimalId: "MOCK-009",
    originalUrl: "https://example.org/mock/adopt/waffles",
    name: "Waffles",
    breedRaw: "Corgi / Dachshund",
    ageRaw: "5 years",
    sexRaw: "Spayed Female",
    sizeRaw: "Small",
    weightRaw: "22 lbs",
    colorRaw: "Red / White",
    statusRaw: "Available",
    // no city/county/coords at all -> geocodePrecision unknown, tests UI fallback
    primaryPhotoUrl: "https://placedog.net/500/400?id=71",
    photoUrls: ["https://placedog.net/500/400?id=71", "https://placedog.net/500/405?id=72"],
    biographyRaw:
      "Waffles is a low-rider with big opinions and a bigger heart. Location being finalized as she transfers between foster homes.",
    goodWithDogs: null,
    goodWithCats: false,
    apartmentFriendly: true,
    energyLevel: "medium",
    spayedNeutered: true,
  }),
  dog({
    sourceAnimalId: "MOCK-010",
    originalUrl: "https://example.org/mock/adopt/duchess",
    name: "Duchess",
    breedRaw: "Great Pyrenees",
    ageRaw: "7 years",
    sexRaw: "Female",
    sizeRaw: "X-Large",
    weightRaw: "98 lbs",
    colorRaw: "White",
    statusRaw: "Available - Longterm Resident",
    city: "San Luis Obispo",
    county: "San Luis Obispo",
    latitude: 35.3191,
    longitude: -120.6877,
    geocodePrecision: "campus",
    primaryPhotoUrl: "https://placedog.net/500/400?id=81",
    photoUrls: ["https://placedog.net/500/400?id=81"],
    biographyRaw:
      "Duchess has been waiting 8 months for a home with room to patrol. Calm, watchful, gentle with people; prefers to be the only pet.",
    goodWithDogs: false,
    goodWithCats: false,
    goodWithKids: true,
    urgentNotes: "Long-term resident — waived adoption fee.",
    adoptionFee: "$0 (waived)",
    energyLevel: "low",
  }),
  dog({
    sourceAnimalId: "MOCK-011",
    originalUrl: "https://example.org/mock/adopt/scooter",
    name: "Scooter",
    breedRaw: "Miniature Poodle Mix",
    ageRaw: "9 years",
    sexRaw: "Male",
    sizeRaw: "Small",
    weightRaw: "14 lbs",
    colorRaw: "Apricot",
    statusRaw: "Medical Hold",
    city: "San Francisco",
    county: "San Francisco",
    latitude: 37.7666,
    longitude: -122.4108,
    geocodePrecision: "campus",
    primaryPhotoUrl: "https://placedog.net/500/400?id=91",
    photoUrls: ["https://placedog.net/500/400?id=91"],
    holdNotes: "Medical hold — dental surgery this week, available after recovery.",
    specialNeeds: "Dental extractions; soft food for 2 weeks.",
    spayedNeutered: true,
    vaccinated: true,
  }),
  dog({
    sourceAnimalId: "MOCK-012",
    originalUrl: "https://example.org/mock/adopt/biscuit",
    name: "Biscuit",
    breedRaw: "Dachshund",
    ageRaw: "4 years",
    sexRaw: "Spayed Female",
    sizeRaw: "Small",
    weightRaw: "16 lbs",
    colorRaw: "Black / Tan",
    statusRaw: "Available",
    city: "San Mateo",
    county: "San Mateo",
    latitude: 37.5629,
    longitude: -122.3255,
    geocodePrecision: "city",
    primaryPhotoUrl: "https://placedog.net/500/400?id=101",
    photoUrls: ["https://placedog.net/500/400?id=101", "https://placedog.net/500/406?id=102"],
    description: "Classic black-and-tan doxie, professional burrower.",
    biographyRaw:
      "Biscuit is a textbook dachshund: tunnels under every blanket, announces the mail, adores her people. Fine with calm dogs, untested with cats. The saved-search demo dog.",
    goodWithDogs: true,
    goodWithKids: true,
    houseTrained: true,
    apartmentFriendly: true,
    energyLevel: "medium",
    spayedNeutered: true,
    vaccinated: true,
    microchipped: true,
    adoptionFee: "$175",
  }),
];

export const mockAdapter: SourceAdapter = {
  system: "mock",
  parserVersion: "mock-1.0.0",
  async crawl(ctx: AdapterContext): Promise<AdapterResult> {
    ctx.log(`mock adapter returning ${MOCK_DOGS.length} synthetic dogs`);
    return {
      dogs: MOCK_DOGS,
      totalReportedBySource: MOCK_DOGS.length,
      pagesVisited: 1,
      detailPagesVisited: 0,
      detailsAttempted: 0,
      detailsSucceeded: 0,
      detailsFailed: 0,
      paginationCompleted: true,
      detailExtractionCompleted: true,
      warnings: [],
      paginationTrace: [
        { url: ctx.source.listingUrl, page: 1, resultCount: MOCK_DOGS.length },
      ],
      htmlHash: null,
    };
  },
};
