import type { NewAdoptionSourceRow } from "@/db/schema";

/**
 * California source registry.
 *
 * `enabled: true` means the adapter was verified against the live source
 * (2026-07-01 investigation) and is safe for personal low-frequency fetching.
 * Disabled sources are seeded so their metadata, permission notes, and
 * investigation findings are preserved for later implementation.
 *
 * Coordinates are approximate shelter/campus locations for map display.
 * permission/robots fields are operational notes, not legal conclusions.
 */

export type SourceDef = Omit<NewAdoptionSourceRow, "createdAt" | "updatedAt">;

export const SOURCE_REGISTRY: SourceDef[] = [
  // ------------------------------------------------------------------ mock
  {
    id: "mock_bay_area",
    name: "Scout Mock Shelter Network",
    sourceSystem: "mock",
    adapterType: "mock",
    listingUrl: "mock://bay-area",
    baseUrl: null,
    region: "Bay Area",
    city: "San Francisco",
    county: "San Francisco",
    state: "CA",
    latitude: 37.7749,
    longitude: -122.4194,
    geocodePrecision: "city",
    priority: "low",
    enabled: false,
    permissionStatus: "not_applicable",
    robotsStatus: "not_applicable",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: false,
    requiresDetailPages: false,
    notes:
      "Dev/testing only — synthetic dogs for unit tests and UI work. Disabled so the live database holds real listings only.",
    requestDelayMs: 0,
    timeoutMs: 5000,
  },

  // -------------------------------------------------------- 24Petconnect
  {
    id: "24pc_santa_cruz",
    name: "Santa Cruz County Animal Shelter",
    sourceSystem: "24petconnect",
    adapterType: "petconnect24",
    listingUrl: "https://24petconnect.com/SantaCruzAdoptable?at=DOG",
    baseUrl: "https://24petconnect.com",
    region: "Central Coast / Bay Area",
    city: "Santa Cruz",
    county: "Santa Cruz",
    state: "CA",
    postalCode: "95062",
    latitude: 36.9721,
    longitude: -121.9829,
    geocodePrecision: "campus",
    phone: "(831) 454-7200",
    websiteUrl: "https://www.scanimalshelter.org",
    adoptionProcessUrl: "https://www.scanimalshelter.org/adopt",
    priority: "high",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "no_robots",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: true,
    notes:
      "Verified 2026-07-01: server-rendered grid, 'Animals: 1-17 of 17' count header, ?index= pagination, rich detail pages (bio, intake date, shelter contact).",
    requestDelayMs: 2000,
    maxPagesPerRun: 20,
    maxDetailPagesPerRun: 150,
  },
  {
    id: "24pc_santa_clara",
    name: "Santa Clara County Animal Services",
    sourceSystem: "24petconnect",
    adapterType: "petconnect24",
    listingUrl: "https://24petconnect.com/SCCAdoptablePets?at=DOG",
    baseUrl: "https://24petconnect.com",
    region: "Bay Area",
    city: "San Martin",
    county: "Santa Clara",
    state: "CA",
    postalCode: "95046",
    latitude: 37.0857,
    longitude: -121.5883,
    geocodePrecision: "campus",
    websiteUrl: "https://asd.sccgov.org",
    priority: "high",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "no_robots",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: true,
    notes: "Same 24Petconnect markup as Santa Cruz tenant (verified system 2026-07-01).",
    requestDelayMs: 2000,
    maxPagesPerRun: 20,
    maxDetailPagesPerRun: 150,
  },
  {
    id: "24pc_sacramento_county",
    name: "Sacramento County Animal Care (Bradshaw Shelter)",
    sourceSystem: "24petconnect",
    adapterType: "petconnect24",
    listingUrl: "https://24petconnect.com/SacramentoCountyAdoptablePets?at=DOG",
    baseUrl: "https://24petconnect.com",
    region: "Sacramento",
    city: "Sacramento",
    county: "Sacramento",
    state: "CA",
    postalCode: "95827",
    latitude: 38.5372,
    longitude: -121.3405,
    geocodePrecision: "campus",
    websiteUrl: "https://animalcare.saccounty.gov",
    priority: "high",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "no_robots",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: true,
    notes: "Same 24Petconnect markup as Santa Cruz tenant.",
    requestDelayMs: 2000,
    maxPagesPerRun: 30,
    maxDetailPagesPerRun: 200,
  },
  {
    id: "24pc_riverside_county",
    name: "Riverside County Animal Services",
    sourceSystem: "24petconnect",
    adapterType: "petconnect24",
    listingUrl: "https://24petconnect.com/RVSDAdopt?at=DOG",
    baseUrl: "https://24petconnect.com",
    region: "Inland Empire",
    city: "Jurupa Valley",
    county: "Riverside",
    state: "CA",
    latitude: 33.9664,
    longitude: -117.4557,
    geocodePrecision: "campus",
    websiteUrl: "https://rcdas.org",
    priority: "high",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "no_robots",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: true,
    notes:
      "Same 24Petconnect markup as Santa Cruz tenant. High volume county system (~400 dogs) — a from-scratch crawl needs two runs to hydrate all detail pages within budget.",
    requestDelayMs: 2000,
    maxPagesPerRun: 30,
    maxDetailPagesPerRun: 250,
  },
  {
    id: "24pc_slo_county",
    name: "San Luis Obispo County Animal Services",
    sourceSystem: "24petconnect",
    adapterType: "petconnect24",
    listingUrl: "https://24petconnect.com/SLOCAdopt?at=DOG",
    baseUrl: "https://24petconnect.com",
    region: "Central Coast",
    city: "San Luis Obispo",
    county: "San Luis Obispo",
    state: "CA",
    latitude: 35.3191,
    longitude: -120.6877,
    geocodePrecision: "campus",
    websiteUrl: "https://www.slocounty.ca.gov/departments/health-agency/animal-services",
    priority: "medium",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "no_robots",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: true,
    notes:
      "Starter page includes mixed species; adapter requests ?at=DOG and additionally filters non-dog records by species/breed text.",
    requestDelayMs: 2000,
    maxPagesPerRun: 20,
    maxDetailPagesPerRun: 150,
  },

  // ------------------------------------------------- LA County DACC (API)
  {
    id: "lac_dacc",
    name: "LA County Animal Care & Control (all care centers)",
    sourceSystem: "custom_lac_dacc",
    adapterType: "lacdacc",
    listingUrl: "https://animalcare.lacounty.gov/dacc-search/?PageNumber=1&PageSize=9&SortType=0",
    baseUrl: "https://animalcare.lacounty.gov",
    region: "Los Angeles County",
    city: "Los Angeles",
    county: "Los Angeles",
    state: "CA",
    latitude: 34.0522,
    longitude: -118.2437,
    geocodePrecision: "county",
    websiteUrl: "https://animalcare.lacounty.gov",
    adoptionProcessUrl: "https://animalcare.lacounty.gov/adoption-process/",
    priority: "critical",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "allows",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: false,
    notes:
      "Verified 2026-07-01: WordPress plugin exposes signed JSON API (/wp-json/wppro-acc/v1/get/animals). Signature+timestamp scraped from the search page per run and expire quickly. ~787 dogs across 7 care centers. Preserves kennel statuses (ADOPTION PENDING, STRAY WAIT, RESCUE ONLY, ID HOLD, OTHER HOLD, RTGH...). robots.txt Crawl-delay: 10 honored. Detail API uses a different page signature — skipped in v1; human detail URLs preserved.",
    requestDelayMs: 10000, // robots.txt Crawl-delay: 10
    timeoutMs: 30000,
    maxPagesPerRun: 15, // 15 pages x 100/page = 1500 dog capacity
    maxDetailPagesPerRun: 0,
  },

  // ------------------------------------------------------- direct rescues
  {
    id: "muttville",
    name: "Muttville Senior Dog Rescue",
    sourceSystem: "direct_html",
    adapterType: "muttville",
    listingUrl: "https://muttville.org/available_mutts",
    baseUrl: "https://muttville.org",
    region: "Bay Area",
    city: "San Francisco",
    county: "San Francisco",
    state: "CA",
    postalCode: "94103",
    latitude: 37.765,
    longitude: -122.4124,
    geocodePrecision: "campus",
    email: "adoptions@muttville.org",
    websiteUrl: "https://muttville.org",
    adoptionProcessUrl: "https://muttville.org/how_to_adopt",
    priority: "high",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "no_rules",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: false,
    requiresDetailPages: true,
    notes:
      "Verified 2026-07-01: all available mutts on one server-rendered page (~51), detail pages have #id/breed/sex/weight/size/est-age/status + bio + photos. Dogs live in fosters around the Bay Area; HQ coordinates used (campus precision). Senior dogs only.",
    requestDelayMs: 1200,
    maxPagesPerRun: 3,
    maxDetailPagesPerRun: 120,
  },

  // --------------------------------------------------------- ShelterBuddy
  {
    id: "marin_humane",
    name: "Marin Humane",
    sourceSystem: "shelterbuddy",
    adapterType: "shelterbuddy",
    listingUrl: "https://marinpets.shelterbuddy.com/search/?newsearch=yes",
    baseUrl: "https://marinpets.shelterbuddy.com",
    region: "Bay Area",
    city: "Novato",
    county: "Marin",
    state: "CA",
    postalCode: "94949",
    latitude: 38.0788,
    longitude: -122.5241,
    geocodePrecision: "campus",
    phone: "(415) 883-4621",
    websiteUrl: "https://marinhumane.org",
    adoptionProcessUrl: "https://marinhumane.org/adopt/adoption-process/",
    priority: "high",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "no_robots",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: true,
    notes:
      "Verified 2026-07-01: classic ShelterBuddy (ASP), GET /search/searchResults.asp?task=search&searchType=4&animalType=3,16 returns server-rendered cards; detail pages have breed/second-breed/sex/color/weight/desexed/age/size/health flags/bio.",
    requestDelayMs: 1500,
    maxPagesPerRun: 10,
    maxDetailPagesPerRun: 80,
  },
  {
    id: "sd_humane_shelterbuddy",
    name: "San Diego Humane Society (ShelterBuddy mirror)",
    sourceSystem: "shelterbuddy",
    adapterType: "shelterbuddy",
    listingUrl: "https://sandiegohumanesocietypets.shelterbuddy.com/search/?newsearch=yes",
    baseUrl: "https://sandiegohumanesocietypets.shelterbuddy.com",
    region: "San Diego",
    city: "San Diego",
    county: "San Diego",
    state: "CA",
    latitude: 32.7526,
    longitude: -117.1998,
    geocodePrecision: "campus",
    websiteUrl: "https://sdhumane.org",
    contactUrl: "https://sdhumane.org/about-us/contact-us/",
    adoptionProcessUrl: "https://sdhumane.org/adopt/adoption-process/",
    priority: "critical",
    enabled: false,
    permissionStatus: "needs_review",
    robotsStatus: "no_robots",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: true,
    notes:
      "DISABLED permanently: this ShelterBuddy search mirror returned only 4 dogs while the main site shows hundreds — superseded by sd_humane_main, whose adapter reads the first-party AWS feed behind sdhumane.org/adopt/available-pets/.",
    requestDelayMs: 1500,
  },

  // ------------------------------------------------ LA Animal Services
  {
    id: "laas",
    name: "LA Animal Services",
    sourceSystem: "custom_laas",
    adapterType: "laas",
    listingUrl: "https://www.laanimalservices.com/search/dogs",
    baseUrl: "https://www.laanimalservices.com",
    region: "Los Angeles",
    city: "Los Angeles",
    county: "Los Angeles",
    state: "CA",
    latitude: 34.0522,
    longitude: -118.2437,
    geocodePrecision: "city",
    websiteUrl: "https://www.laanimalservices.com",
    adoptionProcessUrl: "https://www.laanimalservices.com/adopt",
    priority: "critical",
    enabled: true,
    permissionStatus: "operator_reviewed_2026_07",
    robotsStatus: "disallows_listing_path",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: true,
    useBrowserHeaders: true,
    robotsOverrideReason:
      "robots.txt is Drupal core's unmodified stock template; its /search/ disallow targets the core search module, and /pet/ detail pages are not disallowed. Using the /search/dogs pager (~31 pages) is ~60x lighter on their servers than sweeping the 2,089-URL sitemap. Operator decision 2026-07-01: crawl at low frequency with browser-profile headers (the CDN 403s all non-browser clients, including robots.txt fetches).",
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: true,
    notes:
      "Verified 2026-07-01: Drupal views pager (?page=0..N, 24 dogs/page), cards carry name/animal id/PetHarbor photo; /pet/{id} detail pages carry sex, size, color, breed, lifestage, care status, available date, shelter location + address. 6 city shelters (East Valley, West Valley, North Central, Chesterfield Square, Harbor, West LA).",
    requestDelayMs: 1500,
    timeoutMs: 30000,
    maxPagesPerRun: 45,
    maxDetailPagesPerRun: 900,
  },
  {
    id: "rocket_dog_rescue",
    name: "Rocket Dog Rescue",
    sourceSystem: "shelterluv",
    adapterType: "shelterluv",
    listingUrl: "https://www.rocketdogrescue.org/adopt/adoptees/",
    baseUrl: "https://www.rocketdogrescue.org",
    region: "Bay Area",
    city: "Oakland",
    county: "Alameda",
    state: "CA",
    latitude: 37.8044,
    longitude: -122.2712,
    geocodePrecision: "city",
    websiteUrl: "https://www.rocketdogrescue.org",
    adoptionProcessUrl: "https://www.rocketdogrescue.org/adopt/",
    priority: "medium",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "allows",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: false,
    requiresDetailPages: true,
    notes:
      "Verified 2026-07-02: the shelterluv_embed.js widget's Vue iframe calls a first-party JSON feed GET new.shelterluv.com/api/v3/available-animals/184?saved_query=7104 that returns every available animal (dogs + a few guinea pigs; adapter filters to dogs) with uniqueId (RCKT-A-####), exact birthday, breed, colors, weight band, photos, and a public_url detail link. Single call, no pagination. Foster-based rescue; dogs live around the Bay Area, mapped at the Oakland hub (city precision). Reusable for any ShelterLuv org via SHELTERLUV_TENANTS. Updated 2026-07-03: the feed has NO bio field — the org's write-up (kennel_description) only lives on each dog's public_url embed page, so a bounded detail-page pass fetches it per dog.",
    requestDelayMs: 1500,
    timeoutMs: 30000,
    maxPagesPerRun: 2,
    maxDetailPagesPerRun: 150,
  },

  // ------------------------------------------ seeded, not yet investigated
  {
    id: "front_street",
    name: "Front Street Animal Shelter (City of Sacramento)",
    sourceSystem: "adopets",
    adapterType: "adopets",
    listingUrl:
      "https://www.cityofsacramento.gov/community-development/animal-care/adoptions/adopt-a-dog/adopt-a-shelter-dog",
    baseUrl: "https://www.cityofsacramento.gov",
    region: "Sacramento",
    city: "Sacramento",
    county: "Sacramento",
    state: "CA",
    postalCode: "95818",
    latitude: 38.5646,
    longitude: -121.5184,
    geocodePrecision: "campus",
    websiteUrl: "https://www.cityofsacramento.gov/community-development/animal-care",
    adoptionProcessUrl:
      "https://www.cityofsacramento.gov/community-development/animal-care/adoptions",
    priority: "high",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "unchecked",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: false,
    notes:
      "Verified 2026-07-02: the city page embeds the Adopets iframe (shelter_uuid f7631c97-…, dog specie_uuid 7eeb0882-…, same global dog uuid as Long Beach). Served by the existing adopets adapter via Adopets' anonymous public API (session-request → pet/find, offset paging). Original listing URLs point at adopt.adopets.com/pet/{uuid}; animal codes (A######) present. Front Street is the City of Sacramento's shelter (distinct from the Sacramento County 24Petconnect source).",
    requestDelayMs: 1200,
    maxPagesPerRun: 30,
    maxDetailPagesPerRun: 0,
  },
  {
    id: "long_beach_acs",
    name: "Long Beach Animal Care Services",
    sourceSystem: "adopets",
    adapterType: "adopets",
    listingUrl: "https://www.longbeach.gov/acs/our-animals/adoptions/dogs/",
    baseUrl: "https://www.longbeach.gov",
    region: "Los Angeles / Long Beach",
    city: "Long Beach",
    county: "Los Angeles",
    state: "CA",
    latitude: 33.8115,
    longitude: -118.0885,
    geocodePrecision: "campus",
    websiteUrl: "https://www.longbeach.gov/acs",
    adoptionProcessUrl: "https://www.longbeach.gov/acs/our-animals/adoptions/",
    priority: "high",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "unchecked",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: false,
    notes:
      "Verified 2026-07-01: both longbeach.gov/acs and adoptlb.com embed the Adopets iframe (shelter_uuid 1d7b348f-…, dog specie_uuid 7eeb0882-…). The adapter uses Adopets' public anonymous API (session-request → pet/find, 12/page offset paging) — the same access the iframe grants any visitor. Original listing URLs point at adopt.adopets.com/pet/{uuid}. Animal codes (A######) present.",
    requestDelayMs: 1200,
    maxPagesPerRun: 30,
    maxDetailPagesPerRun: 0,
  },
  {
    id: "sf_acc",
    name: "San Francisco Animal Care & Control",
    sourceSystem: "24petconnect",
    adapterType: "petconnect24",
    listingUrl: "https://24petconnect.com/SFACCadopt?at=DOG",
    baseUrl: "https://24petconnect.com",
    region: "Bay Area",
    city: "San Francisco",
    county: "San Francisco",
    state: "CA",
    postalCode: "94103",
    latitude: 37.7666,
    longitude: -122.4108,
    geocodePrecision: "campus",
    phone: "(415) 554-6364",
    websiteUrl: "https://www.sfanimalcare.org",
    adoptionProcessUrl: "https://www.sfanimalcare.org/adopt/",
    priority: "critical",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "no_robots",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: true,
    notes:
      "Verified 2026-07-01: sfanimalcare.org/adoptable-animals/dogs/ embeds an iframe of 24petconnect.com/SFACCadopt?at=DOG — same 24Petconnect markup as the county tenants, so the existing petconnect24 adapter serves it directly.",
    requestDelayMs: 2000,
    maxPagesPerRun: 20,
    maxDetailPagesPerRun: 150,
  },
  {
    id: "sf_spca",
    name: "SF SPCA",
    sourceSystem: "direct_html",
    adapterType: "sfspca",
    listingUrl: "https://www.sfspca.org/adoptions/dogs/",
    baseUrl: "https://www.sfspca.org",
    region: "Bay Area",
    city: "San Francisco",
    county: "San Francisco",
    state: "CA",
    postalCode: "94103",
    latitude: 37.7649,
    longitude: -122.4117,
    geocodePrecision: "campus",
    websiteUrl: "https://www.sfspca.org",
    adoptionProcessUrl: "https://www.sfspca.org/adoptions/",
    priority: "critical",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "unchecked",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: true,
    notes:
      "Verified 2026-07-01: first-party WP REST endpoint /wp-json/sfspca/v1/adoption?page=N (12/page, all species — adapter filters dogs). Permalink detail pages (/sfspca-adoption/{id}/) add age, exact weight, bio, photos. Sites: Mission Adoption Center, Pacific Heights.",
    requestDelayMs: 1500,
    maxPagesPerRun: 15,
    maxDetailPagesPerRun: 80,
  },
  {
    id: "milo_foundation",
    name: "Milo Foundation",
    sourceSystem: "unknown",
    adapterType: "unknown",
    listingUrl: "https://www.milofoundation.org/dogs-for-adoption/",
    baseUrl: "https://www.milofoundation.org",
    region: "Bay Area",
    city: "Richmond",
    county: "Contra Costa",
    state: "CA",
    latitude: 37.9236,
    longitude: -122.3864,
    geocodePrecision: "campus",
    websiteUrl: "https://www.milofoundation.org",
    priority: "high",
    enabled: false,
    permissionStatus: "unreviewed",
    robotsStatus: "unchecked",
    notes:
      "NOT YET INVESTIGATED. Also operates a sanctuary in Willits. Check whether listing grid is server-rendered.",
  },
  {
    id: "oakland_animal_services",
    name: "Oakland Animal Services",
    sourceSystem: "direct_html",
    adapterType: "oakland",
    listingUrl: "https://www.oaklandanimalservices.org/adopt/dogs/",
    baseUrl: "https://www.oaklandanimalservices.org",
    region: "Bay Area",
    city: "Oakland",
    county: "Alameda",
    state: "CA",
    postalCode: "94601",
    latitude: 37.7817,
    longitude: -122.2282,
    geocodePrecision: "campus",
    websiteUrl: "https://www.oaklandanimalservices.org",
    adoptionProcessUrl: "https://www.oaklandanimalservices.org/adopt/how-to-adopt/",
    priority: "high",
    enabled: true,
    permissionStatus: "operator_reviewed_2026_07",
    robotsStatus: "unchecked",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: true,
    useBrowserHeaders: true,
    needsJavaScript: false,
    hasPagination: false,
    requiresDetailPages: true,
    notes:
      "Verified 2026-07-01: WordPress pet portal backed by RescueGroups. The dogs page server-renders every current dog as #animalCell divs with data attributes (name/sex/weight/exact age/shelter-or-foster/intake/identifier); detail pages add full breed, color, spay/neuter, microchip, vaccination, bio, multi-photo gallery. Site returns 403 to non-browser user agents → browser-profile headers (operator decision 2026-07-01), low frequency.",
    requestDelayMs: 1500,
    maxPagesPerRun: 3,
    maxDetailPagesPerRun: 150,
  },
  {
    id: "hssv",
    name: "Humane Society Silicon Valley",
    sourceSystem: "unknown",
    adapterType: "unknown",
    listingUrl: "https://www.hssv.org/dogs/",
    baseUrl: "https://www.hssv.org",
    region: "Bay Area",
    city: "Milpitas",
    county: "Santa Clara",
    state: "CA",
    postalCode: "95035",
    latitude: 37.4361,
    longitude: -121.8925,
    geocodePrecision: "campus",
    websiteUrl: "https://www.hssv.org",
    priority: "high",
    enabled: false,
    permissionStatus: "unreviewed",
    robotsStatus: "unchecked",
    notes: "NOT YET INVESTIGATED.",
  },
  {
    id: "phs_spca",
    name: "Peninsula Humane Society & SPCA",
    sourceSystem: "unknown",
    adapterType: "unknown",
    listingUrl: "https://phs-spca.org/adopt/dogs/",
    baseUrl: "https://phs-spca.org",
    region: "Bay Area",
    city: "Burlingame",
    county: "San Mateo",
    state: "CA",
    postalCode: "94010",
    latitude: 37.5934,
    longitude: -122.3627,
    geocodePrecision: "campus",
    websiteUrl: "https://phs-spca.org",
    priority: "high",
    enabled: false,
    permissionStatus: "unreviewed",
    robotsStatus: "unchecked",
    notes: "NOT YET INVESTIGATED.",
  },
  {
    id: "sd_humane_main",
    name: "San Diego Humane Society",
    sourceSystem: "shelterbuddy",
    adapterType: "sdhumane",
    listingUrl: "https://sdhumane.org/adopt/available-pets/",
    baseUrl: "https://sdhumane.org",
    region: "San Diego",
    city: "San Diego",
    county: "San Diego",
    state: "CA",
    latitude: 32.7526,
    longitude: -117.1998,
    geocodePrecision: "campus",
    phone: "(619) 299-7012",
    websiteUrl: "https://sdhumane.org",
    contactUrl: "https://sdhumane.org/about-us/contact-us/",
    adoptionProcessUrl: "https://sdhumane.org/adopt/adoption-process/",
    priority: "critical",
    enabled: true,
    permissionStatus: "reviewed_ok_for_personal_use",
    robotsStatus: "unchecked",
    safeForPersonalLowFrequencyFetching: true,
    blocksAutomation: false,
    needsJavaScript: false,
    hasPagination: false,
    requiresDetailPages: false,
    notes:
      "Verified 2026-07-01: their available-pets widget calls a first-party AWS API Gateway feed (embedded in the page source) that returns every available animal across all campuses in one GET — ShelterBuddy-backed. ~340 dogs of ~790 animals. Campuses: San Diego (Gaines St), Escondido, El Cajon, Oceanside. Supersedes the under-reporting sandiegohumanesocietypets.shelterbuddy.com mirror.",
    requestDelayMs: 2000,
    timeoutMs: 60000,
    maxPagesPerRun: 3,
    maxDetailPagesPerRun: 0,
  },
];
